name: Released Version Workflow

on:
  pull_request:
    branches:
      - master
  
jobs:
  Run_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
                
      - name: Set up virtual environment
        run: |
          python -m venv env
          source env/bin/activate
          pip install wheel==0.30.0 setuptools==70.0.0
          pip install azdev
          azdev --version
          azdev setup -r ./
          az extension list --output table
          azdev test azure-devops